// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VAlgo.Modules.ProblemManagement.Infractructure.Persistence;

#nullable disable

namespace VAlgo.Modules.ProblemManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProblemManagementDbContext))]
    [Migration("20260315150330_Problems_V2")]
    partial class Problems_V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("companies", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Constraints")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("constraints");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("Editorial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("editorial");

                    b.Property<string>("FollowUp")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("follow_up");

                    b.Property<string>("InputFormat")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("input_format");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit_kb");

                    b.Property<string>("OutputFormat")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("output_format");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_ms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("problems", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemClassificationRef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_classifications", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemCompanyRef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_companies", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemExample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Explanation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("explanation");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("input");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("output");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_examples", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemHint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_hints", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.SimilarProblemRef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("similar_problem_id");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("similar_problems", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ComparisonStrategy")
                        .HasColumnType("integer")
                        .HasColumnName("output_comparion_strategy");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<bool>("IsSample")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sample");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_test_cases", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", b =>
                {
                    b.OwnsMany("VAlgo.Modules.ProblemManagement.Domain.ValueObjects.AllowedLanguage", "AllowedLanguages", b1 =>
                        {
                            b1.Property<Guid>("ProblemId")
                                .HasColumnType("uuid")
                                .HasColumnName("problem_id");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("language");

                            b1.HasKey("ProblemId", "Value");

                            b1.ToTable("problem_allowed_languages", "problems");

                            b1.WithOwner()
                                .HasForeignKey("ProblemId");
                        });

                    b.Navigation("AllowedLanguages");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemClassificationRef", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("Classifications")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemCompanyRef", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("Companies")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemExample", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("Examples")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemHint", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("Hints")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.SimilarProblemRef", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("SimilarProblems")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("TestCases")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("Companies");

                    b.Navigation("Examples");

                    b.Navigation("Hints");

                    b.Navigation("SimilarProblems");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
