// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VAlgo.Modules.ProblemManagement.Infractructure.Persistence;

#nullable disable

namespace VAlgo.Modules.ProblemManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProblemManagementDbContext))]
    [Migration("20260123161907_Initial_ProblemManagement")]
    partial class Initial_ProblemManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit_kb");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_ms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("problems", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemClassificationRef", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_classifications", "problem_classifications");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ComparisonStrategy")
                        .HasColumnType("integer")
                        .HasColumnName("output_comparion_strategy");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<bool>("IsSample")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sample");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("problem_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("problem_id");

                    b.ToTable("problem_test_cases", "problems");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", b =>
                {
                    b.OwnsMany("VAlgo.Modules.ProblemManagement.Domain.ValueObjects.AllowedLanguage", "AllowedLanguages", b1 =>
                        {
                            b1.Property<Guid>("ProblemId")
                                .HasColumnType("uuid")
                                .HasColumnName("problem_id");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("language");

                            b1.HasKey("ProblemId", "Value");

                            b1.ToTable("problem_allowed_languages", "problems");

                            b1.WithOwner()
                                .HasForeignKey("ProblemId");
                        });

                    b.Navigation("AllowedLanguages");
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.ProblemClassificationRef", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("Classifications")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", null)
                        .WithMany("TestCases")
                        .HasForeignKey("problem_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.ProblemManagement.Domain.Aggregates.Problem", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
