FROM node:20-slim

RUN apt-get update && \
    apt-get install -y time && \
    npm install -g typescript ts-node && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m sandbox
USER sandbox

WORKDIR /sandbox