FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN apt-get update && \
    apt-get install -y time && \
    dotnet tool install -g dotnet-script && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="$PATH:/root/.dotnet/tools"

RUN useradd -m sandbox
USER sandbox

WORKDIR /sandbox