// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VAlgo.Modules.Submissions.Infrastructure.Persistence;

#nullable disable

namespace VAlgo.Modules.Submissions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubmissionsDbContext))]
    [Migration("20260304151428_Update-SubmissionsLatest")]
    partial class UpdateSubmissionsLatest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VAlgo.Modules.Submissions.Domain.Aggregates.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FailureReason")
                        .HasColumnType("integer")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer")
                        .HasColumnName("verdict");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_submissions_created_at");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("idx_submissions_problem_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_submissions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_submissions_user_id");

                    b.HasIndex("Status", "RetryCount")
                        .HasDatabaseName("ix_submissions_retry");

                    b.HasIndex("Status", "WorkerId")
                        .HasDatabaseName("ix_submissions_status_worker");

                    b.ToTable("submissions", "submissions");
                });

            modelBuilder.Entity("VAlgo.Modules.Submissions.Domain.Entities.TestCaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MemoryKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_kb");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<int>("TestCaseIndex")
                        .HasColumnType("integer")
                        .HasColumnName("test_case_index");

                    b.Property<int>("TimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_ms");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_test_case_results_submission");

                    b.HasIndex("SubmissionId", "TestCaseIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_test_case_results_submission_case");

                    b.ToTable("submission_test_case_results", "submissions");
                });

            modelBuilder.Entity("VAlgo.Modules.Submissions.Domain.Aggregates.Submission", b =>
                {
                    b.OwnsOne("VAlgo.Modules.Submissions.Domain.ValueObjects.JudgeSummary", "JudgeSummary", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxMemoryKb")
                                .HasColumnType("integer")
                                .HasColumnName("max_memory_kb");

                            b1.Property<int>("MaxTimeMs")
                                .HasColumnType("integer")
                                .HasColumnName("max_time_ms");

                            b1.Property<int>("PassedTestCases")
                                .HasColumnType("integer")
                                .HasColumnName("passed_test_cases");

                            b1.Property<int>("TotalTestCases")
                                .HasColumnType("integer")
                                .HasColumnName("total_test_cases");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.OwnsOne("VAlgo.Modules.Submissions.Domain.ValueObjects.Language", "Language", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("language");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.OwnsOne("VAlgo.Modules.Submissions.Domain.ValueObjects.SourceCodeHash", "SourceCodeHash", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("source_code_hash");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.Navigation("JudgeSummary");

                    b.Navigation("Language")
                        .IsRequired();

                    b.Navigation("SourceCodeHash")
                        .IsRequired();
                });

            modelBuilder.Entity("VAlgo.Modules.Submissions.Domain.Entities.TestCaseResult", b =>
                {
                    b.HasOne("VAlgo.Modules.Submissions.Domain.Aggregates.Submission", null)
                        .WithMany("TestCaseResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VAlgo.Modules.Submissions.Domain.Aggregates.Submission", b =>
                {
                    b.Navigation("TestCaseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
