// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VAlgo.Modules.Submissions.Infrastructure.Persistence;

#nullable disable

namespace VAlgo.Modules.Submissions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubmissionsDbContext))]
    partial class SubmissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VAlgo.Modules.Submissions.Domain.Aggregates.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit_kb");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_ms");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_submissions_created_at");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("idx_submissions_problem_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_submissions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_submissions_user_id");

                    b.ToTable("submissions", "submissions");
                });

            modelBuilder.Entity("VAlgo.Modules.Submissions.Infrastructure.Persistence.Entities.TestCaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<int>("MemoryKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_kb");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<int>("TimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_ms");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("idx_test_case_results_submission_id");

                    b.HasIndex("SubmissionId", "Index")
                        .IsUnique()
                        .HasDatabaseName("uq_test_case_results_submission_id_test_case_index");

                    b.ToTable("test_case_results", "test_case_results");
                });

            modelBuilder.Entity("VAlgo.Modules.Submissions.Domain.Aggregates.Submission", b =>
                {
                    b.OwnsOne("VAlgo.Modules.Submissions.Domain.ValueObjects.JudgeSummary", "JudgeSummary", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxMemoryKb")
                                .HasColumnType("integer")
                                .HasColumnName("max_memory_kb");

                            b1.Property<int>("MaxTimeMs")
                                .HasColumnType("integer")
                                .HasColumnName("max_time_ms");

                            b1.Property<int>("PassedTestCases")
                                .HasColumnType("integer")
                                .HasColumnName("passed_test_cases");

                            b1.Property<int>("TotalTestCases")
                                .HasColumnType("integer")
                                .HasColumnName("total_test_cases");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.OwnsOne("VAlgo.Modules.Submissions.Domain.ValueObjects.Language", "Language", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("language");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.OwnsOne("VAlgo.Modules.Submissions.Domain.ValueObjects.SourceCodeHash", "SourceCodeHash", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("source_code_hash");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.Navigation("JudgeSummary");

                    b.Navigation("Language")
                        .IsRequired();

                    b.Navigation("SourceCodeHash")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
