// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VAlgo.Modules.Contests.Infrastructure.Persistence;

#nullable disable

namespace VAlgo.Modules.Contests.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContestsDbContext))]
    [Migration("20260306164041_Initial_Contests")]
    partial class Initial_Contests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Aggregates.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("contests", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastSubmissionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submission_at");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer")
                        .HasColumnName("penalty");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ContestId", "UserId")
                        .IsUnique();

                    b.ToTable("contest_participants", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("problem_code");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ContestId", "Order")
                        .IsUnique();

                    b.ToTable("contest_problems", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestParticipant", b =>
                {
                    b.HasOne("VAlgo.Modules.Contests.Domain.Aggregates.Contest", null)
                        .WithMany("Participants")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestProblem", b =>
                {
                    b.HasOne("VAlgo.Modules.Contests.Domain.Aggregates.Contest", null)
                        .WithMany("Problems")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Aggregates.Contest", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Problems");
                });
#pragma warning restore 612, 618
        }
    }
}
