// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VAlgo.Modules.Contests.Infrastructure.Persistence;

#nullable disable

namespace VAlgo.Modules.Contests.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContestsDbContext))]
    partial class ContestsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Aggregates.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowPractice")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_practice");

                    b.Property<bool>("AllowVirtual")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_virtual");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("FreezeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("freeze_at");

                    b.Property<bool>("IsLeaderboardFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_leaderboard_frozen");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<DateTime?>("RegistrationEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_end_time");

                    b.Property<DateTime?>("RegistrationStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_start_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("TotalSubmissions")
                        .HasColumnType("integer")
                        .HasColumnName("total_submissions");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("contests", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registered");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer")
                        .HasColumnName("penalty");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("integer")
                        .HasColumnName("submission_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ContestId", "UserId")
                        .IsUnique();

                    b.ToTable("contest_participants", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("problem_code");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ContestId", "Order")
                        .IsUnique();

                    b.HasIndex("ContestId", "ProblemId")
                        .IsUnique();

                    b.ToTable("contest_problems", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ContestId", "ProblemId");

                    b.HasIndex("ContestId", "UserId");

                    b.ToTable("contest_submissions", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ParticipantProblemStat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContestParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_participant_id");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_solved");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime?>("SolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solved_at");

                    b.Property<Guid?>("VirtualContestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("virtual_contest_session_id");

                    b.Property<int>("WrongAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_attempts");

                    b.HasKey("Id");

                    b.HasIndex("ContestParticipantId", "ProblemId")
                        .IsUnique()
                        .HasFilter("\"contest_participant_id\" IS NOT NULL");

                    b.HasIndex("VirtualContestSessionId", "ProblemId")
                        .IsUnique()
                        .HasFilter("\"virtual_contest_session_id\" IS NOT NULL");

                    b.ToTable("participant_problem_stats", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.VirtualContestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer")
                        .HasColumnName("penalty");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ContestId", "UserId")
                        .IsUnique();

                    b.ToTable("virtual_contest_sessions", (string)null);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestParticipant", b =>
                {
                    b.HasOne("VAlgo.Modules.Contests.Domain.Aggregates.Contest", null)
                        .WithMany("Participants")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestProblem", b =>
                {
                    b.HasOne("VAlgo.Modules.Contests.Domain.Aggregates.Contest", null)
                        .WithMany("Problems")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestSubmission", b =>
                {
                    b.HasOne("VAlgo.Modules.Contests.Domain.Aggregates.Contest", null)
                        .WithMany("Submissions")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ParticipantProblemStat", b =>
                {
                    b.HasOne("VAlgo.Modules.Contests.Domain.Entities.ContestParticipant", null)
                        .WithMany("ProblemStats")
                        .HasForeignKey("ContestParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VAlgo.Modules.Contests.Domain.Entities.VirtualContestSession", null)
                        .WithMany("ProblemStats")
                        .HasForeignKey("VirtualContestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Aggregates.Contest", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Problems");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.ContestParticipant", b =>
                {
                    b.Navigation("ProblemStats");
                });

            modelBuilder.Entity("VAlgo.Modules.Contests.Domain.Entities.VirtualContestSession", b =>
                {
                    b.Navigation("ProblemStats");
                });
#pragma warning restore 612, 618
        }
    }
}
